In [80]:
import pandas as pd
import numpy as np

from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix, f1_score, precision_score,\
recall_score, confusion_matrix, classification_report, accuracy_score 
from sklearn.model_selection import GridSearchCV, cross_val_score, StratifiedKFold
from sklearn.linear_model import SGDClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.svm import LinearSVC
from sklearn import svm
from sklearn.model_selection import GridSearchCV
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sys import argv
import gc
from sklearn.decomposition import TruncatedSVD
from sklearn.pipeline import Pipeline
from imblearn.pipeline import make_pipeline, Pipeline
from imblearn.combine import SMOTEENN
from sklearn.preprocessing import StandardScaler, Normalizer

In [81]:
path = '/Users/lucia/phd_work/Clpsy/'
features = pd.read_csv(path + 'suicideDetection/features/FreqSentiMotiTopiFea.csv')
#merge with liwc data
liwc = pd.read_csv(path + 'suicideDetection/features/liwcSW.csv')
liwc = liwc.rename(columns = {liwc.columns[2]:'user_id'})
liwcUser = liwc.groupby('user_id').mean().reset_index()
liwcUser = liwcUser.drop(['Source (A)', 'Source (D)'], axis=1)
allfea = pd.merge(features, liwcUser, on = 'user_id', how = 'right')
# merge empath
empath = pd.read_csv(path + 'suicideDetection/features/empathSW.csv')
allfea = pd.merge(allfea, empath, on = 'user_id', how = 'right')
#merge tags
# tags = pd.read_csv(path + 'suicideDetection/features/TagFeaSW.csv')
# allfea = pd.merge(allfea, tags, on = 'user_id', how = 'right')

allfea.shape

(496, 146)

In [75]:
Lmodeltest = pd.read_csv(path + 'data/languageModel/allPtest.csv')
testId = Lmodeltest['user_id']
testId = testId.drop_duplicates(keep='first', inplace=False).to_frame()
X_train = pd.merge(allfea, testId, on = 'user_id', how='right')
y_train = X_train.raw_label 
X_train = X_train.iloc[:, 3:146]
X_train.shape

(248, 143)

In [74]:
#y_train = pd.merge(allfea, testId, on = 'user_id', how='outer')
X_test = allfea[(~allfea.user_id.isin(testId.user_id))]
y_test = X_test.raw_label 
X_test = X_test.iloc[:, 3:146]
X_test.shape


(248, 143)

In [83]:
X = allfea.iloc[:, 3:146]
y = allfea.raw_label
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=30)

def SGDclassifier(X_train, X_test, y_train, y_test):
    smote_enn = SMOTEENN(random_state=42)

    clf = make_pipeline(smote_enn, StandardScaler(), SGDClassifier(max_iter= 1000))

    parameters = [{'sgdclassifier__alpha': [0.01, 0.05, 0.001, 0.005], 'sgdclassifier__class_weight':['balanced'],
                  'sgdclassifier__loss': ['hinge','log','modified_huber','squared_hinge', 'perceptron'], 
                   'sgdclassifier__penalty':['none','l1','l2']}]

    grid_search_item = GridSearchCV(clf,
                              param_grid = parameters,
                               scoring = 'accuracy',
                               cv = 5,
                               n_jobs = -1)

    grid_search = grid_search_item.fit(X_train, y_train)

    print('Best scores and best parameters')
    print(grid_search.best_score_)
    print(grid_search.best_params_)

    y_true, y_pred = y_test, grid_search.predict(X_test)
    print(classification_report(y_true, y_pred))
    print(confusion_matrix(y_true, y_pred))

SGDclassifier(X_train, X_test, y_train, y_test)

/Users/lucia/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
/Users/lucia/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


Best scores and best parameters
0.4207492795389049
{'sgdclassifier__alpha': 0.005, 'sgdclassifier__class_weight': 'balanced', 'sgdclassifier__loss': 'log', 'sgdclassifier__penalty': 'l1'}
              precision    recall  f1-score   support

           1       0.71      0.64      0.67        42
           2       0.13      0.36      0.19        14
           3       0.24      0.42      0.30        24
           4       0.65      0.29      0.40        69

   micro avg       0.42      0.42      0.42       149
   macro avg       0.43      0.43      0.39       149
weighted avg       0.55      0.42      0.44       149

[[27  7  3  5]
 [ 3  5  4  2]
 [ 2  8 10  4]
 [ 6 18 25 20]]


/Users/lucia/anaconda3/lib/python3.6/site-packages/imblearn/pipeline.py:349: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  Xt = transform.transform(Xt)


In [79]:
Lmodeltest = pd.read_csv(path + 'data/languageModel/allPtest.csv')
testId = Lmodeltest['user_id']
testId = testId.drop_duplicates(keep='first', inplace=False).to_frame()
X_test = pd.merge(allfea, testId, on = 'user_id', how='right')
y_test = X_test.raw_label 
X_test = X_test.iloc[:, 3:146]
X_train = allfea[(~allfea.user_id.isin(testId.user_id))]
y_train = X_train.raw_label 
X_train = X_train.iloc[:, 3:146]
SGDclassifier(X_train, X_test, y_train, y_test)

/Users/lucia/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
/Users/lucia/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


Best scores and best parameters
0.49193548387096775
{'sgdclassifier__alpha': 0.01, 'sgdclassifier__class_weight': 'balanced', 'sgdclassifier__loss': 'modified_huber', 'sgdclassifier__penalty': 'l1'}
              precision    recall  f1-score   support

           1       0.53      0.51      0.52        76
           2       0.16      0.36      0.23        22
           3       0.32      0.24      0.27        55
           4       0.45      0.40      0.42        95

   micro avg       0.40      0.40      0.40       248
   macro avg       0.36      0.38      0.36       248
weighted avg       0.42      0.40      0.40       248

[[39  8  7 22]
 [ 4  8  3  7]
 [12 13 13 17]
 [19 20 18 38]]


/Users/lucia/anaconda3/lib/python3.6/site-packages/imblearn/pipeline.py:349: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  Xt = transform.transform(Xt)


In [34]:
stressed = pd.read_csv(path + 'data/clpsych19_training_data/Stressed.csv')
StressedSW = SW.append(stressed, ignore_index=True)
StressedSW.to_csv(path + 'data/clpsych19_training_data/StressedSW.csv')


In [35]:
path = '/Users/lucia/phd_work/Clpsy/'
allP = pd.read_csv(path + 'data/clpsych19_training_data/Btrain_NoNoise.csv')
SW= pd.read_csv(path + 'data/clpsych19_training_data/Btrain_NoNoise_SW.csv')
SW= pd.read_csv(path + 'data/clpsych19_training_data/Btrain_NoNoise_SW.csv')

labels = pd.read_csv(path + 'data/clpsych19_training_data/crowd_train.csv')
labels = labels.loc[labels['user_id'] > 0]
x_train,x_test = train_test_split(labels,test_size=0.5)

#get test and train file
def mergeFile(file, testSave):
    filetrain = pd.merge(file, x_train, on ='user_id', how ='right')
    filetest = pd.merge(file, x_test, on ='user_id', how ='right')
    filetest.to_csv()
    return filetrain

testSave1 = path + 'data/languageModel/allPtest.csv'
mergeFile(allP, testSave1)

testSave2 = path + 'data/languageModel/SWPtest.csv'
mergeFile(SW, testSave2)

#SWPtrain = pd.merge(SW, x_train, on ='user_id', how ='right')
#SWPtest = pd.merge(SW, x_test, on ='user_id', how ='right')
#SWPtest.to_csv()

print(len(allP))
print(len(allPtrain))
print(len(allPtest))

print(len(SW))
print(len(SWPtrain))
print(len(SWPtest))

31553
15728
15825
919
516
403


In [5]:
def getClass(file, Class, savePath):
    a = file.loc[file['raw_label_x'] == Class]
    a = a[['post_body','post_title']]
    a.to_csv(savePath)
    

savePath1 = path + 'data/languageModel/AAll.csv'
savePath2 = path + 'data/languageModel/BAll.csv'
savePath3 = path + 'data/languageModel/CAll.csv'
savePath4 = path + 'data/languageModel/DAll.csv'

ClassA = getClass(allPtrain, 'a', savePath1)
ClassB = getClass(allPtrain, 'b', savePath2)
ClassC = getClass(allPtrain, 'c', savePath3)
ClassD = getClass(allPtrain, 'd', savePath4)

In [7]:
savePath1 = path + 'data/languageModel/ASW.csv'
savePath2 = path + 'data/languageModel/BSW.csv'
savePath3 = path + 'data/languageModel/CSW.csv'
savePath4 = path + 'data/languageModel/DSW.csv'

ClassA = getClass(SWPtrain, 'a', savePath1)
ClassB = getClass(SWPtrain, 'b', savePath2)
ClassC = getClass(SWPtrain, 'c', savePath3)
ClassD = getClass(SWPtrain, 'd', savePath4)

In [147]:
text = pd.read_csv(path + 'data/clpsych19_training_data/Btrain_NoNoise_SW.csv')
countVect = pd.read_csv(path + 'countVec.csv')
countVect['user_id'] = text['user_id']

#text['post_body'] = text[['post_body','user_id']].groupby(['post_body'])['user_id'].transform(lambda x: ','.join(x))

In [149]:
countVect.iloc[:, 3::]

2    3    4    5         6    7    8    9   10   11   ...     7760  \
0    0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
1    0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
2    0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
3    0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
4    0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
5    0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
6    0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
7    0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
8    0.0  0.0  0.0  0.0  0.128905  0.0  0.0  0.0  0.0  0.0   ...      0.0   
9    0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
10   0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
11   0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
12   0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
13   0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
14   0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
15   0.0  0.0  0.0  0.0  0.074227  0.0  0.0  0.0  0.0  0.0   ...      0.0   
16   0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
17   0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
18   0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
19   0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
20   0.0  0.0  0.0  0.0  0.099227  0.0  0.0  0.0  0.0  0.0   ...      0.0   
21   0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
22   0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
23   0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
24   0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
25   0.0  0.0  0.0  0.0  0.034543  0.0  0.0  0.0  0.0  0.0   ...      0.0   
26   0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
27   0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
28   0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
29   0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
..   ...  ...  ...  ...       ...  ...  ...  ...  ...  ...   ...      ...   
889  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
890  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
891  0.0  0.0  0.0  0.0  0.045894  0.0  0.0  0.0  0.0  0.0   ...      0.0   
892  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
893  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
894  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
895  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
896  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
897  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
898  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
899  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
900  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
901  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
902  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
903  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
904  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
905  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
906  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
907  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
908  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   ...      0.0   
909

In [145]:
countVect.groupby(['user_id']).mean().reset_index()
#text2.to_csv(path+ 'text2.csv')

user_id  Unnamed: 0    0    1    2    3    4    5         6    7  ...   \
0         16       588.5  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
1         56       594.5  0.0  0.0  0.0  0.0  0.0  0.0  0.075383  0.0  ...    
2        137       581.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
3        152       585.5  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
4        370       593.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
5        706       596.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
6        967       600.0  0.0  0.0  0.0  0.0  0.0  0.0  0.023086  0.0  ...    
7        981       604.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
8       1215       577.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
9       1233       578.0  0.0  0.0  0.0  0.0  0.0  0.0  0.115426  0.0  ...    
10      1288       579.0  0.0  0.0  0.0  0.0  0.0  0.0  0.136073  0.0  ...    
11      1318       580.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
12      1419       582.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
13      1489       583.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
14      1500       584.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
15      1526       587.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
16      1610       590.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
17      1690       591.0  0.0  0.0  0.0  0.0  0.0  0.0  0.259520  0.0  ...    
18      1854       592.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
19      2071       823.5  0.0  0.0  0.0  0.0  0.0  0.0  0.032233  0.0  ...    
20      2103       825.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
21      2205       826.0  0.0  0.0  0.0  0.0  0.0  0.0  0.047398  0.0  ...    
22      2370       827.0  0.0  0.0  0.0  0.0  0.0  0.0  0.056690  0.0  ...    
23      2435       828.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
24      2655       829.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
25      2667       830.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
26      2835       836.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
27      2853       842.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
28      3032       843.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
29      3236       844.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
..       ...         ...  ...  ...  ...  ...  ...  ...       ...  ...  ...    
466    49779       732.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
467    49903       733.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
468    49975       734.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
469    50011       355.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
470    50028       356.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
471    50054       357.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
472    50096       358.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
473    50144       359.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
474    50207       360.5  0.0  0.0  0.0  0.0  0.0  0.0  0.028852  0.0  ...    
475    50293       362.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
476    50294       363.0  0.0  0.0  0.0  0.0  0.0  0.0  0.120229  0.0  ...    
477    50386       364.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
478    50464       365.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
479    50477       366.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
480    50571       367.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
481    50602       368.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
482    50604       369.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
483    50624       370.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...    
484    50804       371.0  0.0  0.0  0.0  0.0  0.0  0.0 

In [137]:
for i in text2['post_body']:
    print(i)

0    I was at party. When everyone were having fun....
Name: 22002, dtype: object
1    Hi. So for starters, I take Zoloft, 75g; they ...
Name: 22006, dtype: object
2    I apologize in advance for this being so long....
Name: 22015, dtype: object
3    I made a thread yesterday where I expressed a ...
4                                                  NaN
5                                                  NaN
6    I tried last night, but threw up the pills. I ...
7    ...but I'm pretty depressed. I have intrusive ...
8    That's the name of the poem _PERSON_ wrote as ...
Name: 22134, dtype: object
9     I can't say much but I have transgender FtM fr...
10    I trusted you, ya know. I trusted you with my ...
Name: 22354, dtype: object
11    I know. _URL_ album saved my life one time whe...
12    You don't need to feel alone.I Love You.If you...
13    This has all been inspired by ThoughtlessThink...
14    I'm running a scan on my laptop, so I'll be he...
Name: 22733, dtype: object
15    W

In [134]:
text

Unnamed: 0 post_id  user_id   timestamp     subreddit  \
0            13  2bvvxg    22002  1406494593  SuicideWatch   
1            54  20x9u6    22006  1395339794  SuicideWatch   
2            75   tr7vb    22015  1337230954  SuicideWatch   
3           110   ip6fx    22134  1310621370  SuicideWatch   
4           114   j2ve3    22134  1311911038  SuicideWatch   
5           135   xhk4e    22134  1343792229  SuicideWatch   
6           136   xjsk1    22134  1343885091  SuicideWatch   
7           164  1dlole    22134  1367556447  SuicideWatch   
8           177  1hcjbb    22134  1372564540  SuicideWatch   
9           223  2d7dzp    22354  1407730199  SuicideWatch   
10          276  2ixwz6    22354  1413032208  SuicideWatch   
11          313   nvtcu    22733  1325217943  SuicideWatch   
12          315   ny0m7    22733  1325373549  SuicideWatch   
13          323   o4qwt    22733  1325812118  SuicideWatch   
14          365   qtuww    22733  1331603108  SuicideWatch   
15          432   dbs3c    22913  1284066769  SuicideWatch   
16          871  19lawc    23308  1362340661  SuicideWatch   
17         1184  1xo4tq    23785  1392170727  SuicideWatch   
18         1360  31l4t6    26024  1428288234  SuicideWatch   
19         1376  3evcom    26024  1438066123  SuicideWatch   
20         1377  150jjv    26047  1355780851  SuicideWatch   
21         1397   uu4qn    26174  1339299824  SuicideWatch   
22         1451  141hib    26179  1354256517  SuicideWatch   
23         1490   klnpz    26244  1316532529  SuicideWatch   
24         1497   lb0wl    26244  1318526528  SuicideWatch   
25         1523  2w2kxe    26244  1424090879  SuicideWatch   
26         1533  10lm3b    26306  1348800677  SuicideWatch   
27         1616  2wy8ds    26433  1424749016  SuicideWatch   
28         1617  2x1wk4    26433  1424822874  SuicideWatch   
29         1626   acng1    26474  1260336479  SuicideWatch   
..          ...     ...      ...         ...           ...   
889       30847  2z9uxg     7904  1426538741  SuicideWatch   
890       30858  2ymq67    40034  1426038416  SuicideWatch   
891       30887  2y8gli    40130  1425730607  SuicideWatch   
892       30891   sqwmy    40225  1335314332  SuicideWatch   
893       30895   t9tr2    40225  1336322016  SuicideWatch   
894       30896   tdiv7    40225  1336510412  SuicideWatch   
895       30897   te19u    40225  1336530862  SuicideWatch   
896       30900   tp8aa    40225  1337132249  SuicideWatch   
897       30920   yg13v    40225  1345326566  SuicideWatch   
898       30924  1af4mb    40225  1363458175  SuicideWatch   
899       30945  13x6z4    40424  1354082989  SuicideWatch   
900       30980  2b436z    40448  1405748796  SuicideWatch   
901       30985  2fv4op    40448  1410225437  SuicideWatch   
902       31005   w470l    40522  1341552125  SuicideWatch   
903       31006   wh67t    40522  1342145068  SuicideWatch   
904       31022  1mxyyd    40522  1379915293  SuicideWatch   
905       31024  1nalmp    40522  1380342145  SuicideWatch   
906       31026  1s3jgn    40522  1386184413  SuicideWatch   
907       31027  1vua4o    40522  1390383693  SuicideWatch   
908       31029  2493gt    40522  1398746155  SuicideWatch   
909       31037  38wu4r    40703  1433688305  SuicideWatch   
910       31044  18nk2o    40756  1361046928  SuicideWatch   
911       31060  2ecfzf    40823  1408772050  SuicideWatch   
912       31087   e17tj    40919  1288886264  SuicideWatch   
913       31088   efbwd    40919  1291337482  SuicideWatch   
914       31165  2y6qqd    40976  1425683595  SuicideWatch   
915       31265  1j0dsf    41059  1374730055  SuicideWatch   
916       31382  17xg59    41192  1360065905  SuicideWatch   
917       31439  3hq7g9    41528  1440083738  SuicideWatch   
918       31531  1lpbwg    41711  1378283044  SuicideWatch   

                                            post_title  \
0         Yesterday i turned off cigarette in my hand.   
1                             Not sure what 